replicaCount: 1

image:
  repository: siddharth67/block-buster-dev:7.6.0
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

namespace:
  name: demo-app
  
labels:
  app:
    name: bb-app
    version: 7.x.x
    env: uat