apiVersion: v1
kind: Service
metadata:
  name: block-buster-helm-app
  labels:
    app: {{ .Values.labels.app.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
        app: {{ .Values.labels.app.name }}
        version: {{ .Values.labels.app.version }}
        env: {{ .Values.labels.app.env }}
